# Generated by Django 3.2 on 2023-05-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=3)),
                ('studentsname', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('intime', models.CharField(max_length=4)),
                ('outtime', models.CharField(max_length=4)),
                ('pre', models.CharField(max_length=10)),
                ('abe', models.CharField(max_length=10)),
                ('inform', models.CharField(max_length=10)),
            ],
        ),
    ]
