# Generated by Django 3.2 on 2023-05-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='intime',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='outtime',
            field=models.CharField(max_length=8),
        ),
    ]
